# Generated by Django 3.1.2 on 2020-11-03 18:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
