# Generated by Django 3.1.2 on 2020-11-03 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='next_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='core.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='core.item'),
        ),
    ]
